# Generated by Django 4.1 on 2022-08-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('img_url', models.URLField()),
                ('github_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioItems',
        ),
    ]
