# Generated by Django 4.1 on 2022-08-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='img_url',
        ),
    ]
