# Generated by Django 4.1 on 2022-08-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_testimonial_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
