# Generated by Django 4.1 on 2022-08-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_testimonial_img_url_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
